# Generated by Django 6.0.3 on 2026-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='events/')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('past', 'Passé'), ('cancelled', 'Annulé')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-start_date'],
            },
        ),
    ]
