# Generated by Django 6.0.3 on 2026-03-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('processing', 'En cours'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.product')),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['-created_at'],
            },
        ),
    ]
