# Generated by Django 6.0.3 on 2026-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramme (kg)'), ('sac', 'Sac'), ('tonne', 'Tonne'), ('litre', 'Litre'), ('unite', 'Unité')], default='kg', max_length=10, verbose_name='Unité'),
        ),
    ]
