# Generated by Django 6.0.3 on 2026-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(help_text='Petite phrase qui résume le service.', max_length=255, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône Bootstrap/FontAwesome par ex.", max_length=100, verbose_name='Icône (optionnel)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image illustrative')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
